# Generated by Django 3.0.8 on 2021-01-04 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80, verbose_name='Назва')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('PubDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('PubDate', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('author', models.TextField(blank=True, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='posts_pictures/', verbose_name='Зображення')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Чорновик')),
                ('Tag', models.ManyToManyField(blank=True, related_name='Post_Tag', to='articles.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('body', models.TextField(max_length=5000, verbose_name='Текст')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Post', verbose_name='Пост')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='Батьківський коментар')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
