# Generated by Django 3.0.8 on 2021-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='gratis-png-icono-de-perfil-icono-de-usuario-simple-thumbnail.png', upload_to='authors_pictures/', verbose_name='картинка профілю'),
        ),
    ]
