# Generated by Django 3.0.8 on 2021-03-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL'),
        ),
    ]
